'use client'

import { motion } from 'framer-motion'
import { FaArrowRight, FaPlay } from 'react-icons/fa'
import videoWork from '@/config/video-work.json'
import content from '@/config/content.json'

export default function Hero() {
  const whatsappUrl = `https://wa.me/${content.siteInfo.whatsappNumber}?text=${encodeURIComponent(content.whatsappMessages.general)}`

  return <section className="min-h-[720px] bg-[var(--surface-warm)] pt-20 md:min-h-[760px] md:pt-36"><div className="mx-auto grid w-[calc(100%-48px)] max-w-[1440px] gap-12 pb-16 lg:grid-cols-[1fr_0.72fr] lg:items-center"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.2em] text-[var(--muted)]">Creativstan / Digital Creator</p><p className="mb-7 text-[11px] font-bold uppercase tracking-[0.2em] text-[var(--accent)]">◆ Posters · Invites · Reels · Ads</p><h1 className="display-serif max-w-2xl text-6xl leading-[0.86] md:text-8xl">Your idea.<br />My creativity.<br /><span className="accent-script text-[var(--accent)]">Something worth sharing.</span></h1><p className="mt-8 max-w-xl text-sm leading-relaxed text-[var(--muted)] md:text-base">I&apos;m Sharduli — a digital creator crafting posters, wedding invites, reels, advertisements, branding and visual content for people and businesses.</p><div className="mt-8 flex flex-wrap items-center gap-4"><a href="#stories" className="inline-flex items-center gap-3 rounded-full bg-[var(--accent)] px-6 py-3 text-sm font-bold text-white transition-transform hover:-translate-y-1"><FaPlay className="text-xs" /> See the work</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 rounded-full border border-[var(--border)] px-6 py-3 text-sm font-bold">Let&apos;s create <FaArrowRight className="text-xs" /></a></div></motion.div><motion.a href="#stories" initial={{ opacity: 0, y: 20, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: 0.9, delay: 0.2 }} className="group mx-auto block w-full max-w-[440px] overflow-hidden rounded-2xl bg-[var(--foreground)] p-2 shadow-[0_24px_40px_rgba(40,54,24,0.16)]"><div className="relative aspect-[4/5] overflow-hidden rounded-xl bg-[var(--foreground)]"><img src={videoWork.hero.src} alt={videoWork.hero.alt} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /><span className="absolute bottom-5 left-5 rounded-full bg-[var(--accent)] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-white">Creativstan Intro</span></div></motion.a></div><div className="mx-auto grid w-[calc(100%-48px)] max-w-[1440px] grid-cols-3 border-t border-[var(--border)] py-5 text-xs text-[var(--muted)]"><span><strong className="display-serif block text-2xl text-[var(--foreground)]">Personal</strong>Made around your idea</span><span><strong className="display-serif block text-2xl text-[var(--foreground)]">Custom</strong>No fixed template</span><span><strong className="display-serif block text-2xl text-[var(--foreground)]">Fast</strong>Quick turnaround</span></div></section>
}
