'use client'

import { motion } from 'framer-motion'
import { FaArrowRight } from 'react-icons/fa'
import content from '@/config/content.json'

const packages = [
  { name: 'Basic Poster', price: '₹199', description: 'For simple, clean designs.', features: ['1 custom design', 'Basic editing', 'HD output', '1 revision', '24-hour delivery'], action: 'Order Poster' },
  { name: 'Professional Poster', price: '₹399', description: 'For designs that need a little more.', features: ['Premium composition', 'Custom elements', 'Ultra HD output', 'Unlimited revisions', 'Source files', 'Up to 12-hour delivery'], action: 'Choose This', popular: true },
  { name: 'Premium Reel', price: '₹599', description: 'For social content that moves.', features: ['10-12 second reel', 'Smooth transitions', 'Music sync', 'Motion graphics', 'Multiple formats', 'Same-day delivery'], action: 'Create a Reel' },
  { name: 'Wedding Invite', price: '₹499', description: 'For celebrations worth announcing beautifully.', features: ['Custom theme', 'Animated elements', 'Background music', 'Multiple ceremony cards', '2 revisions', 'Print-ready files'], action: 'Create My Invite' },
]

export default function Pricing() {
  const orderUrl = (name: string) => `https://wa.me/${content.siteInfo.whatsappNumber}?text=${encodeURIComponent(`Hi I want to order ${name}`)}`

  return <section id="pricing" className="section-padding bg-[var(--surface)]"><div className="editorial-container"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="editorial-label mb-5">Starting points</p><h2 className="display-serif max-w-2xl text-6xl leading-[0.86] md:text-8xl">Choose a way<br />to <span className="accent-script text-[var(--accent)]">create.</span></h2></div><p className="max-w-xs text-sm leading-relaxed text-[var(--muted)]">Clear starting prices for everyday creative needs. Bigger ideas can be shaped around you.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{packages.map((plan, index) => <motion.article key={plan.name} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className={`relative flex min-h-[480px] flex-col rounded-2xl border p-6 transition-transform duration-500 hover:-translate-y-2 ${plan.popular ? 'border-[var(--accent)] bg-[var(--background)] shadow-[0_18px_40px_rgba(188,108,37,0.12)]' : 'border-[var(--border)] bg-[var(--background)]/55'}`}>{plan.popular && <span className="editorial-label mb-6 text-[var(--accent)]">Most popular</span>}<h3 className="text-xl font-bold tracking-[-0.03em]">{plan.name}</h3><p className="mt-3 min-h-10 text-sm leading-relaxed text-[var(--muted)]">{plan.description}</p><div className="my-7 border-y border-[var(--border)] py-5"><span className="editorial-label">Starts at</span><p className="display-serif mt-2 text-5xl">{plan.price}</p></div><ul className="space-y-3 text-sm text-[var(--muted)]">{plan.features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-[var(--accent)]">•</span>{feature}</li>)}</ul><a href={orderUrl(plan.name)} target="_blank" rel="noopener noreferrer" className="group mt-auto inline-flex w-fit items-center gap-3 border-b border-[var(--foreground)] pb-2 pt-8 text-xs font-bold uppercase tracking-[0.14em] transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]">{plan.action} <FaArrowRight className="transition-transform group-hover:translate-x-1" /></a></motion.article>)}</div><div className="mt-16 flex flex-col justify-between gap-5 border-t border-[var(--border)] pt-8 md:flex-row md:items-end"><div><p className="editorial-label mb-3">Custom project</p><h3 className="display-serif text-4xl md:text-6xl">Your idea doesn&apos;t have to fit a package.</h3></div><a href={`https://wa.me/${content.siteInfo.whatsappNumber}?text=${encodeURIComponent(content.whatsappMessages.customPackage)}`} target="_blank" rel="noopener noreferrer" className="group inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[0.14em]">Let&apos;s talk <FaArrowRight className="transition-transform group-hover:translate-x-1" /></a></div></div></section>
}
