'use client'

import { motion } from 'framer-motion'
import { FaArrowRight, FaPlay } from 'react-icons/fa'
import portfolioData from '@/config/portfolio.json'

export default function VideoStories() {
  const projects = portfolioData.portfolioItems.slice(0, 8)
  return <section id="stories" className="bg-[var(--surface)] py-24 md:py-32"><div className="mx-auto w-[calc(100%-48px)] max-w-[1440px]"><div className="mb-14 grid gap-8 md:grid-cols-[1fr_0.65fr] md:items-end"><div><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.2em] text-[var(--accent)]">◆ The film wall</p><h2 className="display-serif text-6xl leading-[0.86] md:text-8xl">Real films.<br />Real weddings.</h2></div><p className="max-w-sm text-sm leading-relaxed text-[var(--muted)]">Tap any film to watch it unfold. Each story is shaped around the couple, their families and the way they want to celebrate.</p></div><div className="grid grid-cols-2 gap-x-4 gap-y-12 md:grid-cols-4 md:gap-x-6">{projects.map((project, index) => { const embedUrl = project.embedCode?.match(/src="([^"]+)"/)?.[1]; return <motion.a key={project.id} href={project.canvaLink} target="_blank" rel="noopener noreferrer" initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.05 }} className={`group ${index % 3 === 1 ? 'md:mt-8' : ''}`}><div className={`relative overflow-hidden rounded-xl bg-[var(--foreground)] ${index % 4 === 0 ? 'aspect-[4/5]' : 'aspect-[3/4]'}`}>{embedUrl ? <iframe title={project.title} src={embedUrl} loading="lazy" className="pointer-events-none absolute inset-0 h-full w-full border-0 opacity-90 transition duration-700 group-hover:scale-105" allowFullScreen /> : <div className="flex h-full items-center justify-center text-white"><FaPlay /></div>}<div className="absolute inset-0 flex items-center justify-center bg-black/0 transition-colors group-hover:bg-black/20"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--accent)] text-white opacity-0 transition-opacity group-hover:opacity-100"><FaPlay className="ml-0.5 text-xs" /></span></div></div><div className="mt-4 flex items-start justify-between gap-3"><div><p className="mb-1 text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--muted)]">{project.category}</p><h3 className="text-sm font-semibold">{project.title}</h3></div><FaArrowRight className="mt-1 text-xs transition-transform group-hover:translate-x-1" /></div><p className="mt-2 text-[10px] font-semibold text-[var(--muted)]">{project.isVideo ? 'Watch the film' : 'View project'} →</p></motion.a> })}</div></div></section>
}
